version: "3"

services:

    mongo:
        image: mongo:5.0.6-focal
        ports:
            - 127.0.0.1:27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - ./conf/mongo/init.js:/docker-entrypoint-initdb.d/init.js

    redis:
        image: redis:6.2.6-bullseye
        ports:
            - 127.0.0.1:6379:6379

    api:
        build:
            context: .
            dockerfile: dockerfile
        command: npm start
        depends_on:
            - redis
            - mongo
        environment:
            - PORT=80
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DB=testdb
            - MONGO_USER=test
            - MONGO_PASS=test
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - INVITE_CODE=52ba0369-810f-4694-8344-3df386363250
        ports:
            - 80:80

