version: "3"

services:

    mongo:
        image: mongo:5.0.6-focal
        ports:
            - 127.0.0.1:27017:27017

    redis:
        image: redis:6.2.6-bullseye
        ports:
            - 127.0.0.1:6379:6379

    app:
        build:
            context: .
            dockerfile: dockerfile
        command: npm start
        depends_on:
            - redis
            - mongo
        environment:
            - PORT=80
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DB=test
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 80:80

